BOARD_TAG    = uno
ARDUINO_LIBS = EEPROM Wire SPI RTC
ARDMK_DIR    = /usr/share/arduino
ARDUINO_DIR  = /opt/arduino
ARDUINO_LIB_PATH = /home/andy/Documents/Projects/Arduino/libraries
ARDUINO_PLATFORM_LIB_PATH = /opt/arduino/hardware/arduino/avr/libraries
USER_LIB_PATH = .

include $(ARDMK_DIR)/Arduino.mk
